# Traductor.py
dic_idiomas = {
    "es": {
        "Inicio de sesión": "Inicio de sesión",
        "Iniciar sesión por Face ID": "Iniciar sesión por Face ID", 
        "Usuario, correo, teléfono": "Usuario, correo, teléfono",
        "Contraseña": "Contraseña",
        "Recordar contraseña": "Recordar contraseña",
        "¿Olvidó su contraseña?": "¿Olvidó su contraseña?",
        "Iniciar sesión": "Iniciar sesión",
        "Iniciar sesión con google": "Iniciar sesión con google",
        "Registrarse": "Registrarse",
        "Mostrar": "Mostrar",
        "Ocultar": "Ocultar",
        "Por favor, complete todos los campos.": "Por favor, complete todos los campos.",
        "Usuario o contraseña incorrectos.": "Usuario o contraseña incorrectos.",
        "Inicio de sesión exitoso": "Inicio de sesión exitoso",
        "OK": "OK",
        "Error": "Error",
        
        # Registro
        "Registro": "Registro",
        "Crear una cuenta": "Crear una cuenta",
        "Confirmar contraseña": "Confirmar contraseña",
        "Las contraseñas no coinciden": "Las contraseñas no coinciden",
        "Registro exitoso": "Registro exitoso",
        "Ya tienes una cuenta? Inicia sesión": "Ya tienes una cuenta? Inicia sesión",
        "Volver al inicio de sesión": "Volver al inicio de sesión",
        "Registrar Face ID": "Registrar Face ID", 
        "(Haga clic en el icono para capturar)": "(Haga clic en el icono para capturar)",
        "Nombre completo": "Nombre completo",
        "Correo electrónico": "Correo electrónico", 
        "Nombre de usuario": "Nombre de usuario",
        "Confirme la contraseña": "Confirme la contraseña",
        "Número de teléfono": "Número de teléfono",
        "Fecha de nacimiento (dd/mm/aaaa)": "Fecha de nacimiento (dd/mm/aaaa)",
        "Elegir fecha": "Elegir fecha",
        "Seleccionar": "Seleccionar",
        "Número de tarjeta": "Número de tarjeta",
        "Solo aceptamos Visa y Mastercard": "Solo aceptamos Visa y Mastercard", 
        "Fecha de vencimiento (mm/aa)": "Fecha de vencimiento (mm/aa)",
        "CVV": "CVV",
        "Gustos": "Gustos",
        "Foto de perfil (JPG/JPEG/PNG/SVG)": "Foto de perfil (JPG/JPEG/PNG/SVG)",
        "Ninguna imagen seleccionada": "Ninguna imagen seleccionada",
        "Seleccionar imagen": "Seleccionar imagen",
        "Imagen seleccionada:": "Imagen seleccionada:",
        "Pregunta de seguridad": "Pregunta de seguridad",
        "Seleccione la pregunta de seguridad": "Seleccione la pregunta de seguridad",
        "¿Cuál es el mejor equipo de fútbol en Costa Rica?": "¿Cuál es el mejor equipo de fútbol en Costa Rica?",
        "¿Cuál es la mejor carrera universitaria del mundo?": "¿Cuál es la mejor carrera universitaria del mundo?",
        "¿Profesor favorito de la universidad?": "¿Profesor favorito de la universidad?",
        "Respuesta de seguridad": "Respuesta de seguridad",
        "Términos y condiciones": "Términos y condiciones",
        "¿Acepta los términos y condiciones?": "¿Acepta los términos y condiciones?",
        "⬇ Desplázate hasta el final para aceptar los términos": "⬇ Desplázate hasta el final para aceptar los términos",
        "✓ Ahora puedes aceptar los términos": "✓ Ahora puedes aceptar los términos",
        "Cancelar": "Cancelar",
        "¿Ya tenés cuenta?": "¿Ya tenés cuenta?",
        "Iniciar sesión": "Iniciar sesión",
        
        # Mensajes Face ID
        "Instrucción": "Instrucción",
        "Se capturarán 10 imágenes automáticamente. Presione 'Aceptar' para comenzar la captura.": "Se capturarán 10 imágenes automáticamente. Presione 'Aceptar' para comenzar la captura.",
        "Capturando rostro... (mirá a la cámara)": "Capturando rostro... (mirá a la cámara)",
        "Sin capturas": "Sin capturas",
        "No se capturó ningún rostro.": "No se capturó ningún rostro.",
        "Rostro capturado (pendiente)": "Rostro capturado (pendiente)",
        "Error Face ID": "Error Face ID",
        "Error al iniciar captura:": "Error al iniciar captura:",
        
        # Mensajes de validación
        "Revisá los datos": "Revisá los datos",
        "No se pudo cargar la imagen:": "No se pudo cargar la imagen:",
        
        # Ayuda
        "Ayuda": "Ayuda",
        "Créditos": "Créditos",

        # Personalización GUI
        "Personalización": "Personalización",
        "Personaliza tu tema": "Personaliza tu tema",
        "Elemento": "Elemento", 
        "Intensidad": "Intensidad",
        "Fondo de la app": "Fondo de la app",
        "Texto principal": "Texto principal",
        "Tarjetas / Ventanas": "Tarjetas / Ventanas",
        "Botón primario": "Botón primario", 
        "Botón secundario": "Botón secundario",
        "Baja (clara)": "Baja (clara)",
        "Media (normal)": "Media (normal)",
        "Alta (oscuro)": "Alta (oscuro)",
        "Canción": "Canción",
        "Buscar": "Buscar",
        "Conectar/Repro": "Conectar/Repro",
        "Aplicar": "Aplicar",
        "Cancelar": "Cancelar",
        "Tarjeta de ejemplo": "Tarjeta de ejemplo",
        "Primario": "Primario",
        "Secundario": "Secundario",
        "Presiona ESC para salir | F11 pantalla completa": "Presiona ESC para salir | F11 pantalla completa",
        "Escribe algo para buscar": "Escribe algo para buscar",
        "No encontré resultados": "No encontré resultados",
        "Seleccionado": "Seleccionado",
        "No hay pista seleccionada": "No hay pista seleccionada",
        "No hay dispositivos activos o no es Premium": "No hay dispositivos activos o no es Premium",
        "Reproduciendo": "Reproduciendo",
        "No se pudo reproducir": "No se pudo reproducir",

        # Juego - Dificultad
        "SELECCIONA LA DIFICULTAD": "SELECCIONA LA DIFICULTAD",
        "FÁCIL": "FÁCIL",
        "MEDIO": "MEDIO", 
        "DIFÍCIL": "DIFÍCIL",
        "Perfecto para principiantes": "Perfecto para principiantes",
        "Desafío equilibrado": "Desafío equilibrado",
        "Para expertos en busca de reto": "Para expertos en busca de reto",
        "Presiona ESC para salir • 1=Fácil • 2=Medio • 3=Difícil": "Presiona ESC para salir • 1=Fácil • 2=Medio • 3=Difícil",

        # Juego - Interfaz
        "Avatar vs rooks": "Avatar vs rooks",
        "TIENDA - ROOKS": "TIENDA - ROOKS",
        "MONEDAS: $": "MONEDAS: $",
        "COLOCA TUS ROOKS": "COLOCA TUS ROOKS",
        "Tiempo:": "Tiempo:",
        "Puntaje:": "Puntaje:",
        "Avatars eliminados:": "Avatars eliminados:",
        "Dificultad:": "Dificultad:",
        "Vida:": "Vida:",
        "Daño:": "Daño:",
        "segundos restantes!": "segundos restantes!",

        # Juego - Final
        "GAME OVER": "GAME OVER",
        "¡VICTORIA!": "¡VICTORIA!",
        "Los avatares llegaron a la base": "Los avatares llegaron a la base",
        "Sobreviviste el tiempo con tus rooks": "Sobreviviste el tiempo con tus rooks",
        "Puntaje Final:": "Puntaje Final:",
        "Presiona R para reiniciar": "Presiona R para reiniciar",
        "Presiona F para ver el Salón de la Fama": "Presiona F para ver el Salón de la Fama",
        "¡NUEVO RÉCORD!": "¡NUEVO RÉCORD!",
        "¡TOP 10 - Posición #": "¡TOP 10 - Posición #",
        "Posición: #": "Posición: #",

        # Salón de la Fama
        "SALÓN DE LA FAMA": "SALÓN DE LA FAMA",
        "No hay puntajes registrados": "No hay puntajes registrados",
        "Presiona ESC para volver": "Presiona ESC para volver",

        # Animaciones
        "¡GAME OVER!": "¡GAME OVER!",
        "Has perdido. ¡Intenta de nuevo!": "Has perdido. ¡Intenta de nuevo!",
        "Reiniciar": "Reiniciar",
        "Menú Principal": "Menú Principal",
        "¡YOU WIN!": "¡YOU WIN!",
        "¡Felicidades, has ganado el juego!": "¡Felicidades, has ganado el juego!",
        "¡¡¡Has entrado al SALÓN DE LA FAMA!!!": "¡¡¡Has entrado al SALÓN DE LA FAMA!!!",
        "Ver": "Ver",
        "Bonus! +100 monedas por 3 flecheros eliminados": "¡Bonus! +100 monedas por 3 flecheros eliminados"
    },
    "en": {
        "Inicio de sesión": "Login",
        "Iniciar sesión por Face ID": "Login with Face ID", 
        "Usuario, correo, teléfono": "Username, email, phone",
        "Contraseña": "Password",
        "Recordar contraseña": "Remember password",
        "¿Olvidó su contraseña?": "Forgot your password?",
        "Iniciar sesión": "Sign in",
        "Iniciar sesión con google": "Sign in with Google",
        "Registrarse": "Sign up",
        "Mostrar": "Show",
        "Ocultar": "Hide",
        "Por favor, complete todos los campos.": "Please fill in all fields.",
        "Usuario o contraseña incorrectos.": "Incorrect username or password.",
        "Inicio de sesión exitoso": "Login successful",
        "OK": "OK",
        "Error": "Error",
        
        # Registro
        "Registro": "Registration",
        "Crear una cuenta": "Create an account",
        "Confirmar contraseña": "Confirm password",
        "Las contraseñas no coinciden": "Passwords do not match",
        "Registro exitoso": "Registration successful",
        "Ya tienes una cuenta? Inicia sesión": "Already have an account? Sign in",
        "Volver al inicio de sesión": "Back to login",
        "Registrar Face ID": "Register Face ID", 
        "(Haga clic en el icono para capturar)": "(Click the icon to capture)",
        "Nombre completo": "Full name",
        "Correo electrónico": "Email", 
        "Nombre de usuario": "Username",
        "Confirme la contraseña": "Confirm password",
        "Número de teléfono": "Phone number",
        "Fecha de nacimiento (dd/mm/aaaa)": "Birth date (dd/mm/yyyy)",
        "Elegir fecha": "Choose date",
        "Seleccionar": "Select",
        "Número de tarjeta": "Card number",
        "Solo aceptamos Visa y Mastercard": "We only accept Visa and Mastercard", 
        "Fecha de vencimiento (mm/aa)": "Expiration date (mm/yy)",
        "CVV": "CVV",
        "Gustos": "Preferences",
        "Foto de perfil (JPG/JPEG/PNG/SVG)": "Profile picture (JPG/JPEG/PNG/SVG)",
        "Ninguna imagen seleccionada": "No image selected",
        "Seleccionar imagen": "Select image",
        "Imagen seleccionada:": "Image selected:",
        "Pregunta de seguridad": "Security question",
        "Seleccione la pregunta de seguridad": "Select security question",
        "¿Cuál es el mejor equipo de fútbol en Costa Rica?": "What is the best soccer team in Costa Rica?",
        "¿Cuál es la mejor carrera universitaria del mundo?": "What is the best university career in the world?",
        "¿Profesor favorito de la universidad?": "Favorite university professor?",
        "Respuesta de seguridad": "Security answer",
        "Términos y condiciones": "Terms and conditions",
        "¿Acepta los términos y condiciones?": "Do you accept the terms and conditions?",
        "⬇ Desplázate hasta el final para aceptar los términos": "⬇ Scroll to the bottom to accept the terms",
        "✓ Ahora puedes aceptar los términos": "✓ Now you can accept the terms",
        "Cancelar": "Cancel",
        "¿Ya tenés cuenta?": "Already have an account?",
        "Iniciar sesión": "Sign in",
        
        # Mensajes Face ID
        "Instrucción": "Instruction",
        "Se capturarán 10 imágenes automáticamente. Presione 'Aceptar' para comenzar la captura.": "10 images will be captured automatically. Press 'OK' to start capture.",
        "Capturando rostro... (mirá a la cámara)": "Capturing face... (look at the camera)",
        "Sin capturas": "No captures",
        "No se capturó ningún rostro.": "No face was captured.",
        "Rostro capturado (pendiente)": "Face captured (pending)",
        "Error Face ID": "Face ID Error",
        "Error al iniciar captura:": "Error starting capture:",
        
        # Mensajes de validación
        "Revisá los datos": "Check your data",
        "No se pudo cargar la imagen:": "Could not load image:",
        
        # Ayuda
        "Ayuda": "Help",
        "Créditos": "Credits",

        # Personalización GUI
        "Personalización": "Customization",
        "Personaliza tu tema": "Customize your theme",
        "Elemento": "Element", 
        "Intensidad": "Intensity",
        "Fondo de la app": "App background",
        "Texto principal": "Main text",
        "Tarjetas / Ventanas": "Cards / Windows",
        "Botón primario": "Primary button", 
        "Botón secundario": "Secondary button",
        "Baja (clara)": "Low (light)",
        "Media (normal)": "Medium (normal)",
        "Alta (oscuro)": "High (dark)",
        "Canción": "Song",
        "Buscar": "Search",
        "Conectar/Repro": "Connect/Play",
        "Aplicar": "Apply",
        "Cancelar": "Cancel",
        "Tarjeta de ejemplo": "Example card",
        "Primario": "Primary",
        "Secundario": "Secondary",
        "Presiona ESC para salir | F11 pantalla completa": "Press ESC to exit | F11 fullscreen",
        "Escribe algo para buscar": "Type something to search",
        "No encontré resultados": "No results found",
        "Seleccionado": "Selected",
        "No hay pista seleccionada": "No track selected",
        "No hay dispositivos activos o no es Premium": "No active devices or not Premium",
        "Reproduciendo": "Playing",
        "No se pudo reproducir": "Could not play",

        # Juego - Dificultad
        "SELECCIONA LA DIFICULTAD": "SELECT DIFFICULTY",
        "FÁCIL": "EASY",
        "MEDIO": "MEDIUM", 
        "DIFÍCIL": "HARD",
        "Perfecto para principiantes": "Perfect for beginners",
        "Desafío equilibrado": "Balanced challenge",
        "Para expertos en busca de reto": "For experts seeking challenge",
        "Presiona ESC para salir • 1=Fácil • 2=Medio • 3=Difícil": "Press ESC to exit • 1=Easy • 2=Medium • 3=Hard",

        # Juego - Interfaz
        "Avatar vs rooks": "Avatar vs rooks",
        "TIENDA - ROOKS": "SHOP - ROOKS",
        "MONEDAS: $": "COINS: $",
        "COLOCA TUS ROOKS": "PLACE YOUR ROOKS",
        "Tiempo:": "Time:",
        "Puntaje:": "Score:",
        "Avatars eliminados:": "Avatars eliminated:",
        "Dificultad:": "Difficulty:",
        "Vida:": "Health:",
        "Daño:": "Damage:",
        "segundos restantes!": "seconds remaining!",

        # Juego - Final
        "GAME OVER": "GAME OVER",
        "¡VICTORIA!": "VICTORY!",
        "Los avatares llegaron a la base": "Avatars reached the base",
        "Sobreviviste el tiempo con tus rooks": "You survived the time with your rooks",
        "Puntaje Final:": "Final Score:",
        "Presiona R para reiniciar": "Press R to restart",
        "Presiona F para ver el Salón de la Fama": "Press F to view Hall of Fame",
        "¡NUEVO RÉCORD!": "NEW RECORD!",
        "¡TOP 10 - Posición #": "TOP 10 - Position #",
        "Posición: #": "Position: #",

        # Salón de la Fama
        "SALÓN DE LA FAMA": "HALL OF FAME",
        "No hay puntajes registrados": "No scores registered",
        "Presiona ESC para volver": "Press ESC to return",

        # Animaciones
        "¡GAME OVER!": "GAME OVER!",
        "Has perdido. ¡Intenta de nuevo!": "You lost. Try again!",
        "Reiniciar": "Restart",
        "Menú Principal": "Main Menu",
        "¡YOU WIN!": "YOU WIN!",
        "¡Felicidades, has ganado el juego!": "Congratulations, you won the game!",
        "¡¡¡Has entrado al SALÓN DE LA FAMA!!!": "You entered the HALL OF FAME!!!",
        "Ver": "View",
        "Bonus! +100 monedas por 3 flecheros eliminados": "Bonus! +100 coins for 3 archers eliminated"
    },
    "hu": {
        "Inicio de sesión": "Bejelentkezés",
        "Iniciar sesión por Face ID": "Bejelentkezés arcfelismeréssel", 
        "Usuario, correo, teléfono": "Felhasználónév, email, telefonszám",
        "Contraseña": "Jelszó",
        "Recordar contraseña": "Jelszó megjegyzése",
        "¿Olvidó su contraseña?": "Elfelejtette jelszavát?",
        "Iniciar sesión": "Bejelentkezés",
        "Iniciar sesión con google": "Bejelentkezés Google-lal",
        "Registrarse": "Regisztráció",
        "Mostrar": "Mutat",
        "Ocultar": "Elrejt",
        "Por favor, complete todos los campos.": "Kérjük, töltse ki az összes mezőt.",
        "Usuario o contraseña incorrectos.": "Hibás felhasználónév vagy jelszó.",
        "Inicio de sesión exitoso": "Sikeres bejelentkezés",
        "OK": "OK",
        "Error": "Hiba",
        
        # Registro
        "Registro": "Regisztráció",
        "Crear una cuenta": "Fiók létrehozása",
        "Confirmar contraseña": "Jelszó megerősítése",
        "Las contraseñas no coinciden": "A jelszavak nem egyeznek",
        "Registro exitoso": "Sikeres regisztráció",
        "Ya tienes una cuenta? Inicia sesión": "Már van fiókja? Jelentkezzen be",
        "Volver al inicio de sesión": "Vissza a bejelentkezéshez",
        "Registrar Face ID": "Arcazonosító regisztrálása", 
        "(Haga clic en el icono para capturar)": "(Kattintson az ikonra a rögzítéshez)",
        "Nombre completo": "Teljes név",
        "Correo electrónico": "E-mail cím", 
        "Nombre de usuario": "Felhasználónév",
        "Confirme la contraseña": "Jelszó megerősítése",
        "Número de teléfono": "Telefonszám",
        "Fecha de nacimiento (dd/mm/aaaa)": "Születési dátum (nn/oo/éééé)",
        "Elegir fecha": "Dátum választása",
        "Seleccionar": "Kiválaszt",
        "Número de tarjeta": "Kártyaszám",
        "Solo aceptamos Visa y Mastercard": "Csak Visa és Mastercard-ot fogadunk el", 
        "Fecha de vencimiento (mm/aa)": "Lejárati dátum (hh/éé)",
        "CVV": "CVV",
        "Gustos": "Preferenciák",
        "Foto de perfil (JPG/JPEG/PNG/SVG)": "Profilkép (JPG/JPEG/PNG/SVG)",
        "Ninguna imagen seleccionada": "Nincs kép kiválasztva",
        "Seleccionar imagen": "Kép kiválasztása",
        "Imagen seleccionada:": "Kiválasztott kép:",
        "Pregunta de seguridad": "Biztonsági kérdés",
        "Seleccione la pregunta de seguridad": "Válassza ki a biztonsági kérdést",
        "¿Cuál es el mejor equipo de fútbol en Costa Rica?": "Mi a legjobb labdarúgócsapat Costa Ricában?",
        "¿Cuál es la mejor carrera universitaria del mundo?": "Mi a legjobb egyetemi karrier a világon?",
        "¿Profesor favorito de la universidad?": "Kedvenc egyetemi professzor?",
        "Respuesta de seguridad": "Biztonsági válasz",
        "Términos y condiciones": "Felhasználási feltételek",
        "¿Acepta los términos y condiciones?": "Elfogadja a felhasználási feltételeket?",
        "⬇ Desplázate hasta el final para aceptar los términos": "⬇ Görgessen a végéhez a feltételek elfogadásához",
        "✓ Ahora puedes aceptar los términos": "✓ Most már elfogadhatja a feltételeket",
        "Cancelar": "Mégse",
        "¿Ya tenés cuenta?": "Már van fiókja?",
        "Iniciar sesión": "Bejelentkezés",
        
        # Mensajes Face ID
        "Instrucción": "Utasítás",
        "Se capturarán 10 imágenes automáticamente. Presione 'Aceptar' para comenzar la captura.": "10 kép fog automatikusan készülni. Nyomja meg az 'OK'-t a rögzítés megkezdéséhez.",
        "Capturando rostro... (mirá a la cámara)": "Arc rögzítése... (nézzen a kamerába)",
        "Sin capturas": "Nincs rögzítés",
        "No se capturó ningún rostro.": "Nem rögzített arcot.",
        "Rostro capturado (pendiente)": "Arc rögzítve (függőben)",
        "Error Face ID": "Arcazonosító hiba",
        "Error al iniciar captura:": "Hiba a rögzítés indításakor:",
        
        # Mensajes de validación
        "Revisá los datos": "Ellenőrizze az adatokat",
        "No se pudo cargar la imagen:": "Nem sikerült betölteni a képet:",
        
        # Ayuda
        "Ayuda": "Súgó",
        "Créditos": "Közreműködők",

        # Personalización GUI
        "Personalización": "Testreszabás",
        "Personaliza tu tema": "Testreszabja a témáját",
        "Elemento": "Elem", 
        "Intensidad": "Intenzitás",
        "Fondo de la app": "Alkalmazás háttere",
        "Texto principal": "Fő szöveg",
        "Tarjetas / Ventanas": "Kártyák / Ablakok",
        "Botón primario": "Elsődleges gomb", 
        "Botón secundario": "Másodlagos gomb",
        "Baja (clara)": "Alacsony (világos)",
        "Media (normal)": "Közepes (normál)",
        "Alta (oscuro)": "Magas (sötét)",
        "Canción": "Dal",
        "Buscar": "Keresés",
        "Conectar/Repro": "Csatlakozás/Lejátszás",
        "Aplicar": "Alkalmaz",
        "Cancelar": "Mégse",
        "Tarjeta de ejemplo": "Példa kártya",
        "Primario": "Elsődleges",
        "Secundario": "Másodlagos",
        "Presiona ESC para salir | F11 pantalla completa": "Nyomja meg az ESC-t a kilépéshez | F11 teljes képernyő",
        "Escribe algo para buscar": "Írjon be valamit a kereséshez",
        "No encontré resultados": "Nem találtam eredményt",
        "Seleccionado": "Kiválasztva",
        "No hay pista seleccionada": "Nincs kiválasztott szám",
        "No hay dispositivos activos o no es Premium": "Nincs aktív eszköz vagy nem Premium",
        "Reproduciendo": "Lejátszás",
        "No se pudo reproducir": "Nem sikerült lejátszani",

        # Juego - Dificultad
        "SELECCIONA LA DIFICULTAD": "VÁLASZD KI A NEHÉZSÉGI SZINTET",
        "FÁCIL": "KÖNNYŰ",
        "MEDIO": "KÖZEPES", 
        "DIFÍCIL": "NEHÉZ",
        "Perfecto para principiantes": "Tökéletes kezdőknek",
        "Desafío equilibrado": "Kiegyensúlyozott kihívás",
        "Para expertos en busca de reto": "Szakértőknek, akik kihívást keresnek",
        "Presiona ESC para salir • 1=Fácil • 2=Medio • 3=Difícil": "Nyomj ESC-t a kilépéshez • 1=Könnyű • 2=Közepes • 3=Nehéz",

        # Juego - Interfaz
        "Avatar vs rooks": "Avatar vs rooks",
        "TIENDA - ROOKS": "BOLT - ROOKS",
        "MONEDAS: $": "ÉRMÉK: $",
        "COLOCA TUS ROOKS": "HELYEZD EL A ROOKJAIDAT",
        "Tiempo:": "Idő:",
        "Puntaje:": "Pontszám:",
        "Avatars eliminados:": "Avatarok eltávolítva:",
        "Dificultad:": "Nehézség:",
        "Vida:": "Életerő:",
        "Daño:": "Sebzés:",
        "segundos restantes!": "másodperc maradt!",

        # Juego - Final
        "GAME OVER": "JÁTÉK VÉGE",
        "¡VICTORIA!": "GYŐZELEM!",
        "Los avatares llegaron a la base": "Az avatarok elérték a bázist",
        "Sobreviviste el tiempo con tus rooks": "Túlélted az időt a rookjaiddal",
        "Puntaje Final:": "Végső pontszám:",
        "Presiona R para reiniciar": "Nyomj R-t az újraindításhoz",
        "Presiona F para ver el Salón de la Fama": "Nyomj F-et a Dicsőség Csarnok megtekintéséhez",
        "¡NUEVO RÉCORD!": "ÚJ REKORD!",
        "¡TOP 10 - Posición #": "TOP 10 - # helyezés",
        "Posición: #": "Helyezés: #",

        # Salón de la Fama
        "SALÓN DE LA FAMA": "DICSŐSÉG CSARNOK",
        "No hay puntajes registrados": "Nincsenek regisztrált pontszámok",
        "Presiona ESC para volver": "Nyomj ESC-t a visszatéréshez",

        # Animaciones
        "¡GAME OVER!": "JÁTÉK VÉGE!",
        "Has perdido. ¡Intenta de nuevo!": "Vesztettél. Próbáld újra!",
        "Reiniciar": "Újraindítás",
        "Menú Principal": "Főmenü",
        "¡YOU WIN!": "GYŐZTÉL!",
        "¡Felicidades, has ganado el juego!": "Gratulálunk, megnyerted a játékot!",
        "¡¡¡Has entrado al SALÓN DE LA FAMA!!!": "Beléptél a DICSŐSÉG CSARNOKÁBA!!!",
        "Ver": "Megtekintés",
        "Bonus! +100 monedas por 3 flecheros eliminados": "Bónusz! +100 érme 3 íjász eltávolításáért"
    },
    "ar": {
        "Inicio de sesión": "تسجيل الدخول",
        "Iniciar sesión por Face ID": "تسجيل الدخول بالتعرف على الوجه", 
        "Usuario, correo, teléfono": "اسم المستخدم، البريد الإلكتروني، الهاتف",
        "Contraseña": "كلمة المرور",
        "Recordar contraseña": "تذكر كلمة المرور",
        "¿Olvidó su contraseña?": "نسيت كلمة المرور؟",
        "Iniciar sesión": "تسجيل الدخول",
        "Iniciar sesión con google": "تسجيل الدخول باستخدام Google",
        "Registrarse": "إنشاء حساب",
        "Mostrar": "إظهار",
        "Ocultar": "إخفاء",
        "Por favor, complete todos los campos.": "يرجى ملء جميع الحقول.",
        "Usuario o contraseña incorrectos.": "اسم المستخدم أو كلمة المرور غير صحيحة.",
        "Inicio de sesión exitoso": "تم تسجيل الدخول بنجاح",
        "OK": "موافق",
        "Error": "خطأ",
        
        # Registro
        "Registro": "التسجيل",
        "Crear una cuenta": "إنشاء حساب",
        "Confirmar contraseña": "تأكيد كلمة المرور",
        "Las contraseñas no coinciden": "كلمات المرور غير متطابقة",
        "Registro exitoso": "تم التسجيل بنجاح",
        "Ya tienes una cuenta? Inicia sesión": "لديك حساب بالفعل؟ سجل الدخول",
        "Volver al inicio de sesión": "العودة لتسجيل الدخول",
        "Registrar Face ID": "تسجيل التعرف على الوجه", 
        "(Haga clic en el icono para capturar)": "(انقر على الأيقونة للتقاط)",
        "Nombre completo": "الاسم الكامل",
        "Correo electrónico": "البريد الإلكتروني", 
        "Nombre de usuario": "اسم المستخدم",
        "Confirme la contraseña": "تأكيد كلمة المرور",
        "Número de teléfono": "رقم الهاتف",
        "Fecha de nacimiento (dd/mm/aaaa)": "تاريخ الميلاد (يوم/شهر/سنة)",
        "Elegir fecha": "اختر التاريخ",
        "Seleccionar": "اختر",
        "Número de tarjeta": "رقم البطاقة",
        "Solo aceptamos Visa y Mastercard": "نقبل فقط فيزا وماستركارد", 
        "Fecha de vencimiento (mm/aa)": "تاريخ الانتهاء (شهر/سنة)",
        "CVV": "CVV",
        "Gustos": "التفضيلات",
        "Foto de perfil (JPG/JPEG/PNG/SVG)": "صورة الملف الشخصي (JPG/JPEG/PNG/SVG)",
        "Ninguna imagen seleccionada": "لم يتم اختيار صورة",
        "Seleccionar imagen": "اختر صورة",
        "Imagen seleccionada:": "الصورة المختارة:",
        "Pregunta de seguridad": "سؤال الأمان",
        "Seleccione la pregunta de seguridad": "اختر سؤال الأمان",
        "¿Cuál es el mejor equipo de fútbol en Costa Rica?": "ما هو أفضل فريق كرة قدم في كوستاريكا؟",
        "¿Cuál es la mejor carrera universitaria del mundo?": "ما هي أفضل تخصص جامعي في العالم؟",
        "¿Profesor favorito de la universidad?": "ما هو أستاذك المفضل في الجامعة؟",
        "Respuesta de seguridad": "إجابة الأمان",
        "Términos y condiciones": "الشروط والأحكام",
        "¿Acepta los términos y condiciones?": "هل تقبل الشروط والأحكام؟",
        "⬇ Desplázate hasta el final para aceptar los términos": "⬇ قم بالتمرير إلى الأسفل لقبول الشروط",
        "✓ Ahora puedes aceptar los términos": "✓ يمكنك الآن قبول الشروط",
        "Cancelar": "إلغاء",
        "¿Ya tenés cuenta?": "هل لديك حساب بالفعل؟",
        "Iniciar sesión": "تسجيل الدخول",
        
        # Mensajes Face ID
        "Instrucción": "تعليمات",
        "Se capturarán 10 imágenes automáticamente. Presione 'Aceptar' para comenzar la captura.": "سيتم التقاط 10 صور تلقائيًا. اضغط 'موافق' لبدء الالتقاط.",
        "Capturando rostro... (mirá a la cámara)": "جاري التقاط الوجه... (انظر إلى الكاميرا)",
        "Sin capturas": "لا توجد لقطات",
        "No se capturó ningún rostro.": "لم يتم التقاط أي وجه.",
        "Rostro capturado (pendiente)": "تم التقاط الوجه (معلق)",
        "Error Face ID": "خطأ في التعرف على الوجه",
        "Error al iniciar captura:": "خطأ في بدء الالتقاط:",
        
        # Mensajes de validación
        "Revisá los datos": "راجع بياناتك",
        "No se pudo cargar la imagen:": "تعذر تحميل الصورة:",
        
        # Ayuda
        "Ayuda": "مساعدة",
        "Créditos": "الاعتمادات",

        # Personalización GUI
        "Personalización": "التخصيص",
        "Personaliza tu tema": "خصص سمة التطبيق",
        "Elemento": "العنصر", 
        "Intensidad": "الشدة",
        "Fondo de la app": "خلفية التطبيق",
        "Texto principal": "النص الرئيسي",
        "Tarjetas / Ventanas": "البطاقات / النوافذ",
        "Botón primario": "الزر الأساسي", 
        "Botón secundario": "الزر الثانوي",
        "Baja (clara)": "منخفضة (فاتحة)",
        "Media (normal)": "متوسطة (عادية)",
        "Alta (oscuro)": "عالية (داكنة)",
        "Canción": "الأغنية",
        "Buscar": "بحث",
        "Conectar/Repro": "اتصال/تشغيل",
        "Aplicar": "تطبيق",
        "Cancelar": "إلغاء",
        "Tarjeta de ejemplo": "بطاقة مثال",
        "Primario": "أساسي",
        "Secundario": "ثانوي",
        "Presiona ESC para salir | F11 pantalla completa": "اضغط ESC للخروج | F11 ملء الشاشة",
        "Escribe algo para buscar": "اكتب شيئًا للبحث",
        "No encontré resultados": "لم أجد نتائج",
        "Seleccionado": "محدد",
        "No hay pista seleccionada": "لا توجد أغنية محددة",
        "No hay dispositivos activos o no es Premium": "لا توجد أجهزة نشطة أو ليس حساب بريميوم",
        "Reproduciendo": "جاري التشغيل",
        "No se pudo reproducir": "تعذر التشغيل",

        # Juego - Dificultad
        "SELECCIONA LA DIFICULTAD": "اختر مستوى الصعوبة",
        "FÁCIL": "سهل",
        "MEDIO": "متوسط", 
        "DIFÍCIL": "صعب",
        "Perfecto para principiantes": "مثالي للمبتدئين",
        "Desafío equilibrado": "تحدي متوازن",
        "Para expertos في busca de reto": "للمحترفين الباحثين عن التحدي",
        "Presiona ESC para salir • 1=Fácil • 2=Medio • 3=Difícil": "اضغط ESC للخروج • 1=سهل • 2=متوسط • 3=صعب",

        # Juego - Interfaz
        "Avatar vs rooks": "أفتار ضد الروكس",
        "TIENDA - ROOKS": "المتجر - الروكس",
        "MONEDAS: $": "العملات: $",
        "COLOCA TUS ROOKS": "ضع الروكس الخاصة بك",
        "Tiempo:": "الوقت:",
        "Puntaje:": "النقاط:",
        "Avatars eliminados:": "الآفتارات المزالة:",
        "Dificultad:": "الصعوبة:",
        "Vida:": "الصحة:",
        "Daño:": "الضرر:",
        "segundos restantes!": "ثانية متبقية!",

        # Juego - Final
        "GAME OVER": "انتهت اللعبة",
        "¡VICTORIA!": "انتصار!",
        "Los avatares llegaron a la base": "وصلت الآفتارات إلى القاعدة",
        "Sobreviviste el tiempo con tus rooks": "لقد نجوت من الوقت مع الروكس الخاصة بك",
        "Puntaje Final:": "النقاط النهائية:",
        "Presiona R para reiniciar": "اضغط R لإعادة التشغيل",
        "Presiona F para ver el Salón de la Fama": "اضغط F لعرض قاعة المشاهير",
        "¡NUEVO RÉCORD!": "رقم قياسي جديد!",
        "¡TOP 10 - Posición #": "أفضل 10 - المركز #",
        "Posición: #": "المركز: #",

        # Salón de la Fama
        "SALÓN DE LA FAMA": "قاعة المشاهير",
        "No hay puntajes registrados": "لا توجد نقاط مسجلة",
        "Presiona ESC para volver": "اضغط ESC للعودة",

        # Animaciones
        "¡GAME OVER!": "انتهت اللعبة!",
        "Has perdido. ¡Intenta de nuevo!": "لقد خسرت. حاول مرة أخرى!",
        "Reiniciar": "إعادة التشغيل",
        "Menú Principal": "القائمة الرئيسية",
        "¡YOU WIN!": "لقد فزت!",
        "¡Felicidades, has ganado el juego!": "مبروك، لقد فزت في اللعبة!",
        "¡¡¡Has entrado al SALÓN DE LA FAMA!!!": "لقد دخلت قاعة المشاهير!!!",
        "Ver": "عرض",
        "Bonus! +100 monedas por 3 flecheros eliminados": "مكافأة! +100 عملة لإزالة 3 رماة"
    },
    "hi": {
        "Inicio de sesión": "लॉगिन",
        "Iniciar sesión por Face ID": "फेस आईडी से लॉगिन करें", 
        "Usuario, correo, teléfono": "उपयोगकर्ता नाम, ईमेल, फोन",
        "Contraseña": "पासवर्ड",
        "Recordar contraseña": "पासवर्ड याद रखें",
        "¿Olvidó su contraseña?": "पासवर्ड भूल गए?",
        "Iniciar sesión": "साइन इन",
        "Iniciar sesión con google": "Google से साइन इन करें",
        "Registrarse": "साइन अप",
        "Mostrar": "दिखाएं",
        "Ocultar": "छुपाएं",
        "Por favor, complete todos los campos.": "कृपया सभी फ़ील्ड भरें।",
        "Usuario o contraseña incorrectos.": "गलत उपयोगकर्ता नाम या पासवर्ड।",
        "Inicio de sesión exitoso": "लॉगिन सफल",
        "OK": "ठीक",
        "Error": "त्रुटि",
        
        # Registro
        "Registro": "पंजीकरण",
        "Crear una cuenta": "खाता बनाएं",
        "Confirmar contraseña": "पासवर्ड की पुष्टि करें",
        "Las contraseñas no coinciden": "पासवर्ड मेल नहीं खाते",
        "Registro exitoso": "पंजीकरण सफल",
        "Ya tienes una cuenta? Inicia sesión": "पहले से खाता है? साइन इन करें",
        "Volver al inicio de sesión": "लॉगिन पर वापस जाएं",
        "Registrar Face ID": "फेस आईडी पंजीकृत करें", 
        "(Haga clic en el icono para capturar)": "(कैप्चर करने के लिए आइकन पर क्लिक करें)",
        "Nombre completo": "पूरा नाम",
        "Correo electrónico": "ईमेल", 
        "Nombre de usuario": "उपयोगकर्ता नाम",
        "Confirme la contraseña": "पासवर्ड की पुष्टि करें",
        "Número de teléfono": "फोन नंबर",
        "Fecha de nacimiento (dd/mm/aaaa)": "जन्म तिथि (दिन/महीना/साल)",
        "Elegir fecha": "तिथि चुनें",
        "Seleccionar": "चुनें",
        "Número de tarjeta": "कार्ड नंबर",
        "Solo aceptamos Visa y Mastercard": "हम केवल Visa और Mastercard स्वीकार करते हैं", 
        "Fecha de vencimiento (mm/aa)": "समाप्ति तिथि (महीना/साल)",
        "CVV": "CVV",
        "Gustos": "पसंद",
        "Foto de perfil (JPG/JPEG/PNG/SVG)": "प्रोफाइल पिक्चर (JPG/JPEG/PNG/SVG)",
        "Ninguna imagen seleccionada": "कोई छवि चयनित नहीं",
        "Seleccionar imagen": "छवि चुनें",
        "Imagen seleccionada:": "चयनित छवि:",
        "Pregunta de seguridad": "सुरक्षा प्रश्न",
        "Seleccione la pregunta de seguridad": "सुरक्षा प्रश्न चुनें",
        "¿Cuál es el mejor equipo de fútbol en Costa Rica?": "कोस्टा रिका में सबसे अच्छा फुटबॉल टीम कौन सा है?",
        "¿Cuál es la mejor carrera universitaria del mundo?": "दुनिया में सबसे अच्छी यूनिवर्सिटी करियर कौन सी है?",
        "¿Profesor favorito de la universidad?": "यूनिवर्सिटी में पसंदीदा प्रोफेसर?",
        "Respuesta de seguridad": "सुरक्षा उत्तर",
        "Términos y condiciones": "नियम और शर्तें",
        "¿Acepta los términos y condiciones?": "क्या आप नियम और शर्तें स्वीकार करते हैं?",
        "⬇ Desplázate hasta el final para aceptar los términos": "⬇ शर्तों को स्वीकार करने के लिए नीचे स्क्रॉल करें",
        "✓ Ahora puedes aceptar los términos": "✓ अब आप शर्तों को स्वीकार कर सकते हैं",
        "Cancelar": "रद्द करें",
        "¿Ya tenés cuenta?": "क्या आपके पास पहले से खाता है?",
        "Iniciar sesión": "साइन इन",
        
        # Mensajes Face ID
        "Instrucción": "निर्देश",
        "Se capturarán 10 imágenes automáticamente. Presione 'Aceptar' para comenzar la captura.": "10 छवियां स्वचालित रूप से कैप्चर की जाएंगी। कैप्चर शुरू करने के लिए 'OK' दबाएं।",
        "Capturando rostro... (mirá a la cámara)": "चेहरा कैप्चर हो रहा है... (कैमरे की ओर देखें)",
        "Sin capturas": "कोई कैप्चर नहीं",
        "No se capturó ningún rostro.": "कोई चेहरा कैप्चर नहीं हुआ।",
        "Rostro capturado (pendiente)": "चेहरा कैप्चर हो गया (लंबित)",
        "Error Face ID": "फेस आईडी त्रुटि",
        "Error al iniciar captura:": "कैप्चर शुरू करने में त्रुटि:",
        
        # Mensajes de validación
        "Revisá los datos": "अपना डेटा जांचें",
        "No se pudo cargar la imagen:": "छवि लोड नहीं हो सकी:",
        
        # Ayuda
        "Ayuda": "सहायता",
        "Créditos": "क्रेडिट",

        # Personalización GUI
        "Personalización": "व्यक्तिगतकरण",
        "Personaliza tu tema": "अपनी थीम अनुकूलित करें",
        "Elemento": "तत्व", 
        "Intensidad": "तीव्रता",
        "Fondo de la app": "ऐप की पृष्ठभूमि",
        "Texto principal": "मुख्य पाठ",
        "Tarjetas / Ventanas": "कार्ड / विंडो",
        "Botón primario": "प्राथमिक बटन", 
        "Botón secundario": "द्वितीयक बटन",
        "Baja (clara)": "कम (हल्का)",
        "Media (normal)": "मध्यम (सामान्य)",
        "Alta (oscuro)": "उच्च (गहरा)",
        "Canción": "गाना",
        "Buscar": "खोजें",
        "Conectar/Repro": "कनेक्ट/चलाएं",
        "Aplicar": "लागू करें",
        "Cancelar": "रद्द करें",
        "Tarjeta de ejemplo": "उदाहरण कार्ड",
        "Primario": "प्राथमिक",
        "Secundario": "द्वितीयक",
        "Presiona ESC para salir | F11 pantalla completa": "बाहर निकलने के लिए ESC दबाएं | F11 पूर्ण स्क्रीन",
        "Escribe algo para buscar": "खोजने के लिए कुछ लिखें",
        "No encontré resultados": "मुझे कोई परिणाम नहीं मिला",
        "Seleccionado": "चयनित",
        "No hay pista seleccionada": "कोई ट्रैक चयनित नहीं है",
        "No hay dispositivos activos o no es Premium": "कोई सक्रिय डिवाइस नहीं है या प्रीमियम नहीं है",
        "Reproduciendo": "चल रहा है",
        "No se pudo reproducir": "चलाया नहीं जा सका",

        # Juego - Dificultad
        "SELECCIONA LA DIFICULTAD": "कठिनाई स्तर चुनें",
        "FÁCIL": "आसान",
        "MEDIO": "मध्यम", 
        "DIFÍCIL": "कठिन",
        "Perfecto para principiantes": "शुरुआती लोगों के लिए बिल्कुल सही",
        "Desafío equilibrado": "संतुलित चुनौती",
        "Para expertos en busca de reto": "चुनौती की तलाश में विशेषज्ञों के लिए",
        "Presiona ESC para salir • 1=Fácil • 2=Medio • 3=Difícil": "बाहर निकलने के लिए ESC दबाएं • 1=आसान • 2=मध्यम • 3=कठिन",

        # Juego - Interfaz
        "Avatar vs rooks": "अवतार बनाम रूक्स",
        "TIENDA - ROOKS": "दुकान - रूक्स",
        "MONEDAS: $": "सिक्के: $",
        "COLOCA TUS ROOKS": "अपने रूक्स रखें",
        "Tiempo:": "समय:",
        "Puntaje:": "स्कोर:",
        "Avatars eliminados:": "अवतार हटाए गए:",
        "Dificultad:": "कठिनाई:",
        "Vida:": "स्वास्थ्य:",
        "Daño:": "क्षति:",
        "segundos restantes!": "सेकंड शेष!",

        # Juego - Final
        "GAME OVER": "खेल समाप्त",
        "¡VICTORIA!": "विजय!",
        "Los avatares llegaron a la base": "अवतार आधार तक पहुँच गए",
        "Sobreviviste el tiempo con tus rooks": "आप अपने रूक्स के साथ समय तक जीवित रहे",
        "Puntaje Final:": "अंतिम स्कोर:",
        "Presiona R para reiniciar": "पुनः आरंभ करने के लिए R दबाएं",
        "Presiona F para ver el Salón de la Fama": "हॉल ऑफ फेम देखने के लिए F दबाएं",
        "¡NUEVO RÉCORD!": "नया रिकॉर्ड!",
        "¡TOP 10 - Posición #": "टॉप 10 - स्थान #",
        "Posición: #": "स्थान: #",

        # Salón de la Fama
        "SALÓN DE LA FAMA": "हॉल ऑफ फेम",
        "No hay puntajes registrados": "कोई स्कोर पंजीकृत नहीं है",
        "Presiona ESC para volver": "वापस जाने के लिए ESC दबाएं",

        # Animaciones
        "¡GAME OVER!": "खेल समाप्त!",
        "Has perdido. ¡Intenta de nuevo!": "आप हार गए। फिर से कोशिश करें!",
        "Reiniciar": "पुनः आरंभ करें",
        "Menú Principal": "मुख्य मेनू",
        "¡YOU WIN!": "आप जीत गए!",
        "¡Felicidades, has ganado el juego!": "बधाई हो, आपने खेल जीत लिया!",
        "¡¡¡Has entrado al SALÓN DE LA FAMA!!!": "आप हॉल ऑफ फेम में प्रवेश कर गए!!!",
        "Ver": "देखें",
        "Bonus! +100 monedas por 3 flecheros eliminados": "बोनस! 3 आर्चर हटाने के लिए +100 सिक्के"
    }
}